#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("iAppAndroid.Resource", IsApplication=true)]

namespace iAppAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060008
			public const int ab_background = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int ab_bottom_shadow_1 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int ab_bottom_shadow_2 = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int action_bar_title_color = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int main_background = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int xam_blue = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int xam_dark_blue = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int xam_gray = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int xam_green = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int xam_light_gray = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int xam_purple = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ab_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bell = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bill = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int discrete_shadow = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int fork = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_logo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int iconTable = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int monoandroidsplash = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int roButton = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int taxi = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070012
			public const int Table = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int TaskImage = 2131165203;
			
			// aapt resource value: 0x7f070011
			public const int Time = 2131165201;
			
			// aapt resource value: 0x7f070006
			public const int ToDoDone = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int ToDoImage = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int ToDoTable = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int ToDoTask = 2131165186;
			
			// aapt resource value: 0x7f070009
			public const int linearLayout1 = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public const int linearLayout2 = 2131165197;
			
			// aapt resource value: 0x7f07000b
			public const int myTasks = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int numberOfTasks = 2131165196;
			
			// aapt resource value: 0x7f07000a
			public const int relativeLayout1 = 2131165194;
			
			// aapt resource value: 0x7f07000e
			public const int relativeLayout3 = 2131165198;
			
			// aapt resource value: 0x7f070007
			public const int sliding_tabs = 2131165191;
			
			// aapt resource value: 0x7f07000f
			public const int tablesMap = 2131165199;
			
			// aapt resource value: 0x7f070000
			public const int taskList = 2131165184;
			
			// aapt resource value: 0x7f070010
			public const int task_flow_fragment = 2131165200;
			
			// aapt resource value: 0x7f070008
			public const int viewpager = 2131165192;
			
			// aapt resource value: 0x7f070003
			public const int whatToDoTable = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int whatToDoTask = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CustomList = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ExecuteTask = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int fragment_swiper = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int TaskFlow = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int TaskItem = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int AllTasks = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int MyTasks = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int archive = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int tables = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int XamActionBarStyle = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int XamActionBarTheme = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int XamActionBarTitleStyle = 2131034115;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
